-- MySQL Script generated by MySQL Workbench
-- Mon Dec  5 18:03:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Kapperzaak
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Kapperzaak
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Kapperzaak` DEFAULT CHARACTER SET utf8 ;
USE `Kapperzaak` ;

-- -----------------------------------------------------
-- Table `Kapperzaak`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kapperzaak`.`Location` (
  `idLocation` INT NOT NULL AUTO_INCREMENT,
  `StreetName` VARCHAR(200) NOT NULL,
  `HouseNumber` VARCHAR(50) NOT NULL,
  `City` VARCHAR(100) NOT NULL,
  `PostalCode` VARCHAR(50) NOT NULL,
  `PhoneNumber` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idLocation`),
  UNIQUE INDEX `idLocation_UNIQUE` (`idLocation` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kapperzaak`.`Permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kapperzaak`.`Permissions` (
  `idPermissions` INT NOT NULL AUTO_INCREMENT,
  `AddLocation` TINYINT NOT NULL,
  `DeleteLocation` TINYINT NOT NULL,
  `EditLocation` TINYINT NOT NULL,
  `ViewLocation` TINYINT NOT NULL,
  `AddAppointment` TINYINT NOT NULL,
  `DeleteAppointment` TINYINT NOT NULL,
  `EditAppointment` TINYINT NOT NULL,
  `ViewAppointment` TINYINT NOT NULL,
  `AddTime` TINYINT NOT NULL,
  `DeleteTime` TINYINT NOT NULL,
  `EditTime` TINYINT NOT NULL,
  `ViewTime` TINYINT NOT NULL,
  `AddProduct` TINYINT NOT NULL,
  `DeleteProduct` TINYINT NOT NULL,
  `EditProduct` TINYINT NOT NULL,
  `ViewProduct` TINYINT NOT NULL,
  `AddTreatment` TINYINT NOT NULL,
  `DeleteTreatment` TINYINT NOT NULL,
  `EditTreatment` TINYINT NOT NULL,
  `ViewTreatment` TINYINT NOT NULL,
  `AddUser` TINYINT NOT NULL,
  `DeleteUser` TINYINT NOT NULL,
  `EditUser` TINYINT NOT NULL,
  `ViewUser` TINYINT NOT NULL,
  `AddRole` TINYINT NOT NULL,
  `DeleteRole` TINYINT NOT NULL,
  `EditRole` TINYINT NOT NULL,
  `ViewRole` TINYINT NOT NULL,
  `AddPermissions` TINYINT NOT NULL,
  `DeletePermissions` TINYINT NOT NULL,
  `EditPermissions` TINYINT NOT NULL,
  `ViewPermissions` TINYINT NOT NULL,
  PRIMARY KEY (`idPermissions`),
  UNIQUE INDEX `idPermissions_UNIQUE` (`idPermissions` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kapperzaak`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kapperzaak`.`Role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `idPermissions` INT NOT NULL,
  `Name` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`idRole`),
  UNIQUE INDEX `idRole_UNIQUE` (`idRole` ASC) VISIBLE,
  INDEX `fk_Role_Permissions1_idx` (`idPermissions` ASC) VISIBLE,
  CONSTRAINT `fk_Role_Permissions1`
    FOREIGN KEY (`idPermissions`)
    REFERENCES `Kapperzaak`.`Permissions` (`idPermissions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kapperzaak`.`ArrayList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kapperzaak`.`ArrayList` (
  `idArrayList` INT NOT NULL,
  `idRole` INT NOT NULL,
  `FirstName` VARCHAR(100) NOT NULL,
  `LastName` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(500) NOT NULL,
  `Sex` VARCHAR(200) NOT NULL,
  `PostalCode` VARCHAR(100) NULL,
  `City` VARCHAR(200) NULL,
  `HouseNumber` VARCHAR(50) NULL,
  `StreetName` VARCHAR(300) NULL,
  `Description` VARCHAR(500) NULL,
  `SpecialSkills` VARCHAR(500) NULL,
  PRIMARY KEY (`idArrayList`),
  UNIQUE INDEX `idArrayList_UNIQUE` (`idArrayList` ASC) VISIBLE,
  INDEX `fk_ArrayList_Role1_idx` (`idRole` ASC) VISIBLE,
  CONSTRAINT `fk_ArrayList_Role1`
    FOREIGN KEY (`idRole`)
    REFERENCES `Kapperzaak`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kapperzaak`.`RegisterdUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kapperzaak`.`RegisterdUser` (
  `idRegisterdUser` INT NOT NULL AUTO_INCREMENT,
  `idArrayList` INT NOT NULL,
  `Password` VARCHAR(200) NOT NULL,
  `Email` VARCHAR(500) NOT NULL,
  UNIQUE INDEX `idRegisterdUser_UNIQUE` (`idRegisterdUser` ASC) VISIBLE,
  PRIMARY KEY (`idRegisterdUser`),
  INDEX `fk_RegisterdUser_ArrayList1_idx` (`idArrayList` ASC) VISIBLE,
  UNIQUE INDEX `idArrayList_UNIQUE` (`idArrayList` ASC) VISIBLE,
  CONSTRAINT `fk_RegisterdUser_ArrayList1`
    FOREIGN KEY (`idArrayList`)
    REFERENCES `Kapperzaak`.`ArrayList` (`idArrayList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kapperzaak`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kapperzaak`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) NOT NULL,
  `Price` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`idProduct`),
  UNIQUE INDEX `idProduct_UNIQUE` (`idProduct` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kapperzaak`.`Treatment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kapperzaak`.`Treatment` (
  `idTreatment` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(300) NOT NULL,
  `Duration` VARCHAR(300) NOT NULL,
  `Price` VARCHAR(300) NOT NULL,
  `Description` VARCHAR(300) NULL,
  PRIMARY KEY (`idTreatment`),
  UNIQUE INDEX `idTreatment_UNIQUE` (`idTreatment` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kapperzaak`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kapperzaak`.`Employee` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  `idLocation` INT NOT NULL,
  `idArrayList` INT NOT NULL,
  PRIMARY KEY (`idEmployee`),
  UNIQUE INDEX `idEmployee_UNIQUE` (`idEmployee` ASC) VISIBLE,
  INDEX `fk_Employee_Location1_idx` (`idLocation` ASC) VISIBLE,
  INDEX `fk_Employee_ArrayList1_idx` (`idArrayList` ASC) VISIBLE,
  UNIQUE INDEX `idArrayList_UNIQUE` (`idArrayList` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Location1`
    FOREIGN KEY (`idLocation`)
    REFERENCES `Kapperzaak`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_ArrayList1`
    FOREIGN KEY (`idArrayList`)
    REFERENCES `Kapperzaak`.`ArrayList` (`idArrayList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kapperzaak`.`SeatsAvailible`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kapperzaak`.`SeatsAvailible` (
  `idSeats` INT NOT NULL AUTO_INCREMENT,
  `Date(Time)` VARCHAR(100) NOT NULL,
  `TotalSeats` VARCHAR(100) NULL,
  `SeatsUsed` VARCHAR(100) NOT NULL,
  `SeatsFree` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idSeats`),
  UNIQUE INDEX `idSeats_UNIQUE` (`idSeats` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kapperzaak`.`Screening`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kapperzaak`.`Screening` (
  `idScreening` INT NOT NULL AUTO_INCREMENT,
  `idLocation` INT NOT NULL,
  `idTreatment` INT NOT NULL,
  `idSeatsAvailible` INT NOT NULL,
  PRIMARY KEY (`idScreening`),
  UNIQUE INDEX `idScreening_UNIQUE` (`idScreening` ASC) VISIBLE,
  INDEX `fk_Screening_Treatment_idx` (`idTreatment` ASC) VISIBLE,
  INDEX `fk_Screening_Location1_idx` (`idLocation` ASC) VISIBLE,
  INDEX `fk_Screening_SeatsAvailible1_idx` (`idSeatsAvailible` ASC) VISIBLE,
  CONSTRAINT `fk_Screening_Treatment`
    FOREIGN KEY (`idTreatment`)
    REFERENCES `Kapperzaak`.`Treatment` (`idTreatment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Screening_Location1`
    FOREIGN KEY (`idLocation`)
    REFERENCES `Kapperzaak`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Screening_SeatsAvailible1`
    FOREIGN KEY (`idSeatsAvailible`)
    REFERENCES `Kapperzaak`.`SeatsAvailible` (`idSeats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kapperzaak`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kapperzaak`.`Customer` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `idRegisterdUser` INT NULL,
  `Email` VARCHAR(500) NULL,
  UNIQUE INDEX `idCustomer_UNIQUE` (`idCustomer` ASC) VISIBLE,
  PRIMARY KEY (`idCustomer`),
  INDEX `fk_Customer_RegisterdUser1_idx` (`idRegisterdUser` ASC) VISIBLE,
  UNIQUE INDEX `idRegisterdUser_UNIQUE` (`idRegisterdUser` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_RegisterdUser1`
    FOREIGN KEY (`idRegisterdUser`)
    REFERENCES `Kapperzaak`.`RegisterdUser` (`idRegisterdUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kapperzaak`.`Appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kapperzaak`.`Appointment` (
  `idAppointment` INT NOT NULL AUTO_INCREMENT,
  `Screening_idScreening` INT NOT NULL,
  `idCustomer` INT NOT NULL,
  PRIMARY KEY (`idAppointment`, `Screening_idScreening`),
  UNIQUE INDEX `idAppointment_UNIQUE` (`idAppointment` ASC) VISIBLE,
  INDEX `fk_Appointment_Screening1_idx` (`Screening_idScreening` ASC) VISIBLE,
  INDEX `fk_Appointment_Customer1_idx` (`idCustomer` ASC) VISIBLE,
  UNIQUE INDEX `idCustomer_UNIQUE` (`idCustomer` ASC) VISIBLE,
  CONSTRAINT `fk_Appointment_Screening1`
    FOREIGN KEY (`Screening_idScreening`)
    REFERENCES `Kapperzaak`.`Screening` (`idScreening`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Customer1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `Kapperzaak`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kapperzaak`.`Treatment_has_Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kapperzaak`.`Treatment_has_Employee` (
  `Treatment_idTreatment` INT NOT NULL,
  `Employee_idEmployee` INT NOT NULL,
  PRIMARY KEY (`Treatment_idTreatment`, `Employee_idEmployee`),
  INDEX `fk_Treatment_has_Employee_Employee1_idx` (`Employee_idEmployee` ASC) VISIBLE,
  INDEX `fk_Treatment_has_Employee_Treatment1_idx` (`Treatment_idTreatment` ASC) VISIBLE,
  CONSTRAINT `fk_Treatment_has_Employee_Treatment1`
    FOREIGN KEY (`Treatment_idTreatment`)
    REFERENCES `Kapperzaak`.`Treatment` (`idTreatment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Treatment_has_Employee_Employee1`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `Kapperzaak`.`Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kapperzaak`.`Treatment_has_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kapperzaak`.`Treatment_has_Product` (
  `Treatment_idTreatment` INT NOT NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`Treatment_idTreatment`, `Product_idProduct`),
  INDEX `fk_Treatment_has_Product_Product1_idx` (`Product_idProduct` ASC) VISIBLE,
  INDEX `fk_Treatment_has_Product_Treatment1_idx` (`Treatment_idTreatment` ASC) VISIBLE,
  CONSTRAINT `fk_Treatment_has_Product_Treatment1`
    FOREIGN KEY (`Treatment_idTreatment`)
    REFERENCES `Kapperzaak`.`Treatment` (`idTreatment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Treatment_has_Product_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `Kapperzaak`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kapperzaak`.`Location_has_SeatsAvailible`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kapperzaak`.`Location_has_SeatsAvailible` (
  `Location_idLocation` INT NOT NULL,
  `SeatsAvailible_idSeats` INT NOT NULL,
  PRIMARY KEY (`Location_idLocation`, `SeatsAvailible_idSeats`),
  INDEX `fk_Location_has_SeatsAvailible_SeatsAvailible1_idx` (`SeatsAvailible_idSeats` ASC) VISIBLE,
  INDEX `fk_Location_has_SeatsAvailible_Location1_idx` (`Location_idLocation` ASC) VISIBLE,
  CONSTRAINT `fk_Location_has_SeatsAvailible_Location1`
    FOREIGN KEY (`Location_idLocation`)
    REFERENCES `Kapperzaak`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Location_has_SeatsAvailible_SeatsAvailible1`
    FOREIGN KEY (`SeatsAvailible_idSeats`)
    REFERENCES `Kapperzaak`.`SeatsAvailible` (`idSeats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
