-- MySQL Script generated by MySQL Workbench
-- Tue Dec 20 11:08:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kapperszaakdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kapperszaakdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kapperszaakdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `kapperszaakdb` ;

-- -----------------------------------------------------
-- Table `kapperszaakdb`.`userinformation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kapperszaakdb`.`userinformation` (
  `id_userInformation` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(500) NOT NULL,
  `password` VARCHAR(500) NOT NULL,
  `firstName` VARCHAR(500) NOT NULL,
  `middleName` VARCHAR(500) NOT NULL,
  `LastName` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_userInformation`),
  UNIQUE INDEX `id_userInformation_UNIQUE` (`id_userInformation` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;