insert into product (idProduct, Name, Price, Description) values (1, 'Voyatouch', '$7.92', 'morbi a ipsum integer a nibh in quis justo');
insert into product (idProduct, Name, Price, Description) values (2, 'Fixflex', '$7.63', 'donec dapibus');
insert into product (idProduct, Name, Price, Description) values (3, 'Y-find', '$5.08', 'posuere cubilia curae mauris viverra diam');
insert into product (idProduct, Name, Price, Description) values (4, 'Solarbreeze', '$9.47', 'sed magna at nunc commodo placerat praesent blandit nam');
insert into product (idProduct, Name, Price, Description) values (5, 'Gembucket', '$8.82', 'habitasse platea dictumst');
insert into product (idProduct, Name, Price, Description) values (6, 'Lotlux', '$9.25', 'nunc rhoncus dui vel sem');
insert into product (idProduct, Name, Price, Description) values (7, 'Vagram', '$5.69', 'fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a');
insert into product (idProduct, Name, Price, Description) values (8, 'Span', '$8.99', 'nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue');
insert into product (idProduct, Name, Price, Description) values (9, 'Biodex', '$0.49', 'suscipit');
insert into product (idProduct, Name, Price, Description) values (10, 'Tampflex', '$5.22', 'tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis');
insert into product (idProduct, Name, Price, Description) values (11, 'Mat Lam Tam', '$5.70', 'consequat nulla nisl nunc nisl duis bibendum');
insert into product (idProduct, Name, Price, Description) values (12, 'Alphazap', '$7.24', 'in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit');
insert into product (idProduct, Name, Price, Description) values (13, 'Prodder', '$3.23', 'elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum');
insert into product (idProduct, Name, Price, Description) values (14, 'Asoka', '$5.16', 'at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet');
insert into product (idProduct, Name, Price, Description) values (15, 'Cookley', '$1.20', 'morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed');
insert into product (idProduct, Name, Price, Description) values (16, 'Quo Lux', '$0.38', 'nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel');
insert into product (idProduct, Name, Price, Description) values (17, 'Holdlamis', '$5.60', 'vel nisl duis ac nibh fusce lacus');
insert into product (idProduct, Name, Price, Description) values (18, 'Trippledex', '$4.29', 'in imperdiet et commodo vulputate justo in blandit ultrices enim');
insert into product (idProduct, Name, Price, Description) values (19, 'It', '$9.01', 'facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus');
insert into product (idProduct, Name, Price, Description) values (20, 'Rank', '$7.02', 'aliquam quis turpis eget elit sodales scelerisque');
insert into product (idProduct, Name, Price, Description) values (21, 'Sub-Ex', '$4.77', 'eros viverra eget');
insert into product (idProduct, Name, Price, Description) values (22, 'Bitwolf', '$1.41', 'cubilia curae');
insert into product (idProduct, Name, Price, Description) values (23, 'Zamit', '$6.89', 'pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel');
insert into product (idProduct, Name, Price, Description) values (24, 'Tres-Zap', '$2.27', 'tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet');
insert into product (idProduct, Name, Price, Description) values (25, 'Tempsoft', '$6.37', 'eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa');
insert into product (idProduct, Name, Price, Description) values (26, 'Subin', '$1.53', 'orci pede');
insert into product (idProduct, Name, Price, Description) values (27, 'Sonair', '$8.57', 'parturient montes nascetur ridiculus');
insert into product (idProduct, Name, Price, Description) values (28, 'Trippledex', '$9.38', 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit');
insert into product (idProduct, Name, Price, Description) values (29, 'Zaam-Dox', '$0.47', 'consectetuer adipiscing');
insert into product (idProduct, Name, Price, Description) values (30, 'Rank', '$2.64', 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta');
insert into product (idProduct, Name, Price, Description) values (31, 'Mat Lam Tam', '$3.77', 'et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing');
insert into product (idProduct, Name, Price, Description) values (32, 'Opela', '$2.14', 'varius');
insert into product (idProduct, Name, Price, Description) values (33, 'Zathin', '$6.54', 'pretium nisl ut volutpat sapien arcu sed augue aliquam erat');
insert into product (idProduct, Name, Price, Description) values (34, 'Tampflex', '$5.95', 'tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui');
insert into product (idProduct, Name, Price, Description) values (35, 'Flexidy', '$9.86', 'rhoncus aliquam lacus morbi quis tortor id');
insert into product (idProduct, Name, Price, Description) values (36, 'Prodder', '$3.85', 'egestas metus aenean fermentum donec ut');
insert into product (idProduct, Name, Price, Description) values (37, 'Pannier', '$4.15', 'donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id');
insert into product (idProduct, Name, Price, Description) values (38, 'Bamity', '$5.60', 'platea dictumst morbi vestibulum');
insert into product (idProduct, Name, Price, Description) values (39, 'Viva', '$5.17', 'luctus tincidunt nulla mollis molestie lorem quisque ut');
insert into product (idProduct, Name, Price, Description) values (40, 'Ventosanzap', '$0.17', 'ante vel ipsum');
insert into product (idProduct, Name, Price, Description) values (41, 'Zoolab', '$8.81', 'ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer');
insert into product (idProduct, Name, Price, Description) values (42, 'Prodder', '$4.09', 'nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi');
insert into product (idProduct, Name, Price, Description) values (43, 'Zamit', '$4.29', 'in lacus curabitur at ipsum ac');
insert into product (idProduct, Name, Price, Description) values (44, 'Mat Lam Tam', '$3.43', 'vel lectus in quam fringilla rhoncus mauris enim leo rhoncus');
insert into product (idProduct, Name, Price, Description) values (45, 'Subin', '$7.17', 'id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam');
insert into product (idProduct, Name, Price, Description) values (46, 'Zontrax', '$6.46', 'enim');
insert into product (idProduct, Name, Price, Description) values (47, 'Flexidy', '$2.02', 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at');
insert into product (idProduct, Name, Price, Description) values (48, 'Greenlam', '$9.26', 'vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula');
insert into product (idProduct, Name, Price, Description) values (49, 'Aerified', '$7.46', 'nec nisi volutpat');
insert into product (idProduct, Name, Price, Description) values (50, 'Sub-Ex', '$8.39', 'volutpat in congue');
insert into product (idProduct, Name, Price, Description) values (51, 'Bitchip', '$5.93', 'neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim');
insert into product (idProduct, Name, Price, Description) values (52, 'Sub-Ex', '$7.31', 'congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo');
insert into product (idProduct, Name, Price, Description) values (53, 'Regrant', '$0.22', 'donec diam neque vestibulum eget vulputate');
insert into product (idProduct, Name, Price, Description) values (54, 'Sonsing', '$7.26', 'egestas metus');
insert into product (idProduct, Name, Price, Description) values (55, 'Prodder', '$0.89', 'eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus');
insert into product (idProduct, Name, Price, Description) values (56, 'Sub-Ex', '$2.59', 'suscipit nulla elit ac nulla sed');
insert into product (idProduct, Name, Price, Description) values (57, 'Voyatouch', '$0.37', 'libero quis');
insert into product (idProduct, Name, Price, Description) values (58, 'Redhold', '$2.10', 'eu orci mauris lacinia');
insert into product (idProduct, Name, Price, Description) values (59, 'Lotlux', '$8.76', 'magnis dis parturient montes nascetur ridiculus');
insert into product (idProduct, Name, Price, Description) values (60, 'Stim', '$4.71', 'nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris');
insert into product (idProduct, Name, Price, Description) values (61, 'Solarbreeze', '$8.05', 'non mattis pulvinar nulla pede');
insert into product (idProduct, Name, Price, Description) values (62, 'Fix San', '$0.14', 'nulla justo aliquam quis');
insert into product (idProduct, Name, Price, Description) values (63, 'Greenlam', '$5.30', 'velit vivamus vel nulla eget eros');
insert into product (idProduct, Name, Price, Description) values (64, 'Temp', '$4.65', 'ante ipsum primis in faucibus orci');
insert into product (idProduct, Name, Price, Description) values (65, 'Fixflex', '$1.83', 'at turpis donec posuere metus');
insert into product (idProduct, Name, Price, Description) values (66, 'Zontrax', '$6.67', 'aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet');
insert into product (idProduct, Name, Price, Description) values (67, 'Job', '$7.55', 'posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl');
insert into product (idProduct, Name, Price, Description) values (68, 'Cardguard', '$3.12', 'orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin');
insert into product (idProduct, Name, Price, Description) values (69, 'Holdlamis', '$8.22', 'sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat');
insert into product (idProduct, Name, Price, Description) values (70, 'Otcom', '$9.04', 'enim');
insert into product (idProduct, Name, Price, Description) values (71, 'Zamit', '$5.13', 'pede venenatis');
insert into product (idProduct, Name, Price, Description) values (72, 'Temp', '$4.69', 'curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at');
insert into product (idProduct, Name, Price, Description) values (73, 'Bigtax', '$8.76', 'cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel');
insert into product (idProduct, Name, Price, Description) values (74, 'Aerified', '$9.45', 'morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus');
insert into product (idProduct, Name, Price, Description) values (75, 'Tempsoft', '$1.00', 'pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus');
insert into product (idProduct, Name, Price, Description) values (76, 'Andalax', '$0.81', 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante');
insert into product (idProduct, Name, Price, Description) values (77, 'Trippledex', '$2.43', 'mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque');
insert into product (idProduct, Name, Price, Description) values (78, 'Trippledex', '$0.02', 'mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus');
insert into product (idProduct, Name, Price, Description) values (79, 'Aerified', '$4.51', 'imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed');
insert into product (idProduct, Name, Price, Description) values (80, 'Sonair', '$9.37', 'cursus vestibulum proin eu mi nulla ac enim');
insert into product (idProduct, Name, Price, Description) values (81, 'Ronstring', '$7.73', 'eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc');
insert into product (idProduct, Name, Price, Description) values (82, 'Daltfresh', '$5.01', 'suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue');
insert into product (idProduct, Name, Price, Description) values (83, 'Gembucket', '$4.71', 'duis ac nibh fusce lacus purus aliquet at');
insert into product (idProduct, Name, Price, Description) values (84, 'Job', '$2.74', 'interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus');
insert into product (idProduct, Name, Price, Description) values (85, 'Tin', '$0.86', 'dapibus dolor vel est');
insert into product (idProduct, Name, Price, Description) values (86, 'Lotlux', '$9.59', 'at nibh');
insert into product (idProduct, Name, Price, Description) values (87, 'Namfix', '$1.67', 'viverra dapibus nulla suscipit');
insert into product (idProduct, Name, Price, Description) values (88, 'Stringtough', '$6.86', 'vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium');
insert into product (idProduct, Name, Price, Description) values (89, 'Alpha', '$5.28', 'eget');
insert into product (idProduct, Name, Price, Description) values (90, 'Namfix', '$8.59', 'duis at velit eu est congue elementum in hac habitasse platea dictumst');
insert into product (idProduct, Name, Price, Description) values (91, 'Gembucket', '$9.66', 'semper');
insert into product (idProduct, Name, Price, Description) values (92, 'Transcof', '$4.19', 'mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec');
insert into product (idProduct, Name, Price, Description) values (93, 'Otcom', '$0.89', 'tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor');
insert into product (idProduct, Name, Price, Description) values (94, 'Bitwolf', '$1.32', 'non mauris morbi non lectus aliquam sit');
insert into product (idProduct, Name, Price, Description) values (95, 'Opela', '$0.16', 'ante vestibulum ante ipsum primis in faucibus orci');
insert into product (idProduct, Name, Price, Description) values (96, 'Toughjoyfax', '$0.67', 'porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus');
insert into product (idProduct, Name, Price, Description) values (97, 'Gembucket', '$2.37', 'lacus curabitur at ipsum ac');
insert into product (idProduct, Name, Price, Description) values (98, 'Flexidy', '$4.21', 'amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim');
insert into product (idProduct, Name, Price, Description) values (99, 'Zoolab', '$4.47', 'at nunc commodo placerat praesent blandit nam nulla');
insert into product (idProduct, Name, Price, Description) values (100, 'Andalax', '$7.26', 'sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean');
